org.gradle.jvmargs=-Xmx1024m -XX:MaxMetaspaceSize=512m
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.workers.max=4

android.useAndroidX=true
android.enableJetifier=true
android.compileSdk=34
android.targetSdk=34
android.minSdk=21
android.ndkVersion=25.1.8937393

kotlin.language.version=2.0
kotlin.apiVersion=2.0
kotlin.jvm.target=11
kotlin.code.style=official

android.builtInKotlin=true
android.newDsl=false