// File generated by flutterfire configure
// This file should NOT be edited manually
// But we're creating it manually because of connection issues

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    return android;
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
    appId: '1:667181830171:android:85399beb4fc1d087c4e8be',
    messagingSenderId: '667181830171',
    projectId: 'crux-8aa85',
    storageBucket: 'crux-8aa85.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
    appId: '1:667181830171:ios:XXXXXXXXXXXXXXXXXX',
    messagingSenderId: '667181830171',
    projectId: 'crux-8aa85',
    storageBucket: 'crux-8aa85.appspot.com',
    iosBundleId: 'com.example.crux',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
    appId: '1:667181830171:web:XXXXXXXXXXXXXXXXXX',
    messagingSenderId: '667181830171',
    projectId: 'crux-8aa85',
    authDomain: 'crux-8aa85.firebaseapp.com',
    storageBucket: 'crux-8aa85.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
    appId: '1:667181830171:macos:XXXXXXXXXXXXXXXXXX',
    messagingSenderId: '667181830171',
    projectId: 'crux-8aa85',
    storageBucket: 'crux-8aa85.appspot.com',
    iosBundleId: 'com.example.crux',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX',
    appId: '1:667181830171:windows:XXXXXXXXXXXXXXXXXX',
    messagingSenderId: '667181830171',
    projectId: 'crux-8aa85',
    authDomain: 'crux-8aa85.firebaseapp.com',
    storageBucket: 'crux-8aa85.appspot.com',
  );
}